### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TaylorJonesTRT** [Thestias/Random-Movie-Website#1]
How did you parse the movie data? And if you did csv to sqllite could you explain how?

**Comment by Thestias** [comment]
Hello!

I made a small script to download the data from TheMovieDB API and saved it to a csv file, then i imported the csv to my Django model with DBeaver
It probably isnt the best way to do it, but it was very easy and fast

**Comment by TaylorJonesTRT** [comment]
Do you by chance have a word or video tutorial on how you did that? I'm trying to figure it out myself

**Comment by TaylorJonesTRT** [comment]
Only reason I ask is because you actually inspired one of my first projects and I'm working on migrating it from flask to django and only use Netflix data rather than every movie ever made. I just tried forking your repo and get errors when running the django server. I also tried looking through all of your code to see where the database is stored but I'm guessing it isn't since the errors I'm getting have to do with the table not being created?

**Comment by Thestias** [comment]
This is a good tutorial on how i imported the data into my database: https://dbeaver.com/docs/wiki/Data-transfer/    You need to open the django database with DBeaver, i just left the default database that is sqlite so i dont know if its different if you have a different kidn of db

Yes, the database isnt on the repo because its not really a good idea to store data where the code is supossed to go, to recreate the database after you clone the repo you need to run "python manage.py migration" to apply create the table from the model, including the "randomovie" model.

If you have another kind of error please tell me so i can help you, i also can provide you with the data i used in csv format or the sqlite database with the data already in it

**Comment by TaylorJonesTRT** [comment]
Running Migrate worked for the about page! The homepage still isn't working.

Here's the error that I am currently getting

```Environment:


Request Method: GET
Request URL: http://localhost:8000/

Django Version: 3.0.6
Python Version: 3.8.2
Installed Applications:
['apps.users.apps.UsersConfig',
 'apps.randomovie.apps.RandomovieConfig',
 'crispy_forms',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/Users/taylor/.local/share/virtualenvs/forked-randommovie-o2RORE8g/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/taylor/.local/share/virtualenvs/forked-randommovie-o2RORE8g/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/taylor/.local/share/virtualenvs/forked-randommovie-o2RORE8g/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/taylor/Documents/Programming Projects/forked-randommovie/apps/randomovie/views.py", line 28, in homepage
    rand_movie_id = random.randint(1, ammount_items)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/random.py", line 248, in randint
    return self.randrange(a, b+1)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/random.py", line 226, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))

Exception Type: ValueError at /
Exception Value: empty range for randrange() (1, 1, 0)
```

Also I would love to get the database to use and toy with to learn sqllite and how to use it with Python!

**Comment by Thestias** [comment]
> Exception Value: empty range for randrange() (1, 1, 0)

This error its because the database doesnt have any of the data, here its a little bit of context on why it happens:

In apps/randomovie/views.py  

    def homepage(request):
        ammount_items = Movie.objects.count()
        rand_movie_id = random.randint(1, ammount_items)

ammount_items <- This var returns an integer of the ammount of movies there are in the table(created by the django model)

rand_movie_id <- This one creates a random integer between 1 and ammount_items 

The error occurs because the table its empty of movies so *ammount_items* returns 0

Here is the link to the database : https://mega.nz/file/xNA3nKqT#JNYfgIKTTFW5CFNSH1haO-IIKlaeIMs-lgIbIwAiBt4

**Comment by TaylorJonesTRT** [comment]
Thank you so much! 

Now I can fiddle around and also learn how to use sqlite3

**Comment by Thestias** [comment]
You're welcome, have fun!!

and if you have any questions feel free to ask, altought i am a begginer too
